version: '2'
services:
  splunk:
    container_name: splunk
    image: splunk/splunk:6.5.0-monitor
    environment:
     SPLUNK_START_ARGS: --accept-license --answer-yes
     SPLUNK_ENABLE_LISTEN: 9997
     SPLUNK_ADD: tcp 1514
     SPLUNK_USER: root
    volumes:
     - splunk_data:/opt/splunk/etc
     - splunk_data:/opt/splunk/var
     - /var/lib/docker/containers:/host/containers:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
     - "8000:8000"
     - "9997:9997"
     - "8088:8088"
     - "1514:1514"

volumes:
  splunk_data:
